name: Build and deploy Node.js app to Azure Web App - projetreactexpress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'   # Car tu as choisi Node 22 dans Azure

    - name: Install dependencies
      run: |
        cd server
        npm install

    - name: Build client app
      run: |
        cd ../client/projectreact-main
        npm install
        npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: projetreactexpress
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./server
