name: Build and Deploy Node.js app to Azure Web App - projetreactexpress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install server dependencies
      run: |
        cd server
        npm install

    - name: Build client (React)
      run: |
        cd client/projectreact-main
        npm install
        npm run build

    - name: Copy client build to server
      run: |
        rm -rf server/clientbuild
        cp -r client/projectreact-main/dist server/clientbuild

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'projetreactexpress'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./server
