name: Deploy Fullstack (React + Express) to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 🔹 Installer et builder React
      - name: Build React app
        run: |
          cd client/client
          npm install
          npm run build

      # 🔹 Copier le build React vers Express
      - name: Copy React build to Express
        run: |
          rm -rf server/clientbuild
          cp -r client/client/dist server/clientbuild

      # 🔹 Installer les dépendances backend
      - name: Install backend dependencies
        run: |
          cd server
          npm install

      # 🔹 Zipper le dossier server
      - name: Zip backend for deployment
        run: |
          cd server
          zip -r ../release.zip .

      # 🚀 Déployer vers Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projetreactexpress'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip
