name: Build and deploy Node.js app to Azure Web App - projetreactexpress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server  # ➔ On travaille dans /server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: Install server dependencies
      run: npm install

    - name: Install client dependencies and build
      run: |
        cd ../client/projectreact-main
        npm install
        npm run build
        rm -rf ../../server/clientbuild
        cp -r dist ../../server/clientbuild

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: projetreactexpress
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
